service: gomitter-server
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: [dynamodb:BatchGetItem, dynamodb:Query, dynamodb:PutItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/gomi_tweet2"]]
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/gomi_tweet2/index/*"]]

    - Effect: Allow
      Action: [dynamodb:GetItem, dynamodb:UpdateItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/gomi_sequence2"]]

    - Effect: Allow
      Action: [dynamodb:GetItem, dynamodb:BatchGetItem, dynamodb:PutItem, dynamodb:UpdateItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/gomi2"]]

    - Effect: Allow
      Action: [dynamodb:BatchGetItem, dynamodb:Query, dynamodb:UpdateItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/gomi_rank2"]]

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    GomiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gomi2
        AttributeDefinitions:
          - { AttributeName: gomi_id, AttributeType: S }
        KeySchema:
          - { AttributeName: gomi_id, KeyType: HASH }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    GomiRankTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gomi_rank2
        AttributeDefinitions:
          - { AttributeName: gomi_id,   AttributeType: S }
          - { AttributeName: member_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id, KeyType: HASH }
          - { AttributeName: gomi_id,   KeyType: RANGE }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    GomiSequenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gomi_sequence2
        AttributeDefinitions:
          - { AttributeName: key, AttributeType: S }
        KeySchema:
          - { AttributeName: key, KeyType: HASH }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    GomiTweetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gomi_tweet2
        AttributeDefinitions:
          - { AttributeName: id,        AttributeType: N }
          - { AttributeName: member_id, AttributeType: S }
        KeySchema:
          - { AttributeName: id, KeyType: HASH }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: gomi_tweet2_gsi
            KeySchema:
              - { AttributeName: member_id, KeyType: HASH }
              - { AttributeName: id,        KeyType: RANGE }
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
